#!/usr/bin/env python

import beanbag
import requests
from requests_oauthlib import OAuth1
from urlparse import parse_qs

class OAuthDanceTwitter(beanbag.OAuth10aDance):
    req_token = "https://api.twitter.com/oauth/request_token"
    authorize = "https://api.twitter.com/oauth/authorize"
    acc_token = "https://api.twitter.com/oauth/access_token"

client_key, client_secret = (None, None)
user_key, user_secret = (None, None)

session = requests.Session()

oauthDance = OAuthDanceTwitter(
        client_key=client_key, client_secret=client_secret,
        user_key=user_key, user_secret=user_secret)
oauthDance.ensure_creds(interactive=True)
session.auth = oauthDance.oauth()

twitter = beanbag.BeanBag("https://api.twitter.com/1.1/", ext=".json",
                          session=session)

x = twitter.statuses.user_timeline(screen_name="ajtowns", count=7)
for tweet in x:
    print repr(tweet["text"])

